apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-9999
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-9999
  template:
    metadata:
      labels:
        app: nginx-9999
    spec:
      containers:
      - name: nginx-9999
        image: nginx:latest
        ports:
        - containerPort: 9999
---
apiVersion: v1
kind: Service
metadata:
  name: ngx-service-9999
  labels:
    app: nginx-9999
spec:
  selector:
    app: nginx-9999
  ports:
  - port: 9999
    targetPort: 9999
